### ISSUE TITLE
[Suggestion] hit crystal 

### ISSUE THREAD

**Issue by Itman33** [Volcanware/Envy-Client#12]
### Describe the feature

add a oby place and crystal place so there a way to hit crystal

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **repository**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Volcan4436** [comment]
Can you please give me detail as we have an AutoCrystal Module and might implement this into AutoCrystal

**Comment by Volcan4436** [comment]
Closing this issue

Reason: lacking information
