### ISSUE TITLE
[Suggestion] packet mine

### ISSUE THREAD

**Issue by Itman33** [Volcanware/Envy-Client#13]
### Describe the feature

just skid packet mine from medior client

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **repository**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Volcan4436** [comment]
This has been Fixed and is readded
Thank you for posting this suggestion
