### ISSUE TITLE
[Bug] Waypoints icon folder the path is wrong in Waypoints.java

### ISSUE THREAD

**Issue by martingamer128** [Volcanware/Envy-Client#30]
### Describe the bug

It gave me a crash when starting up so I decided to investigate and I realized that the path of the waypoints is wrong in Waypoints.java on line 209 the correct path is /assets/mathax/textures/icons/waypoints/ while the Previous path that was wrong was /assets/mathax/icons/waypoints/ and that's why the game didn't start

### Steps to reproduce

```bash
Start the game by compiling the jar in branch 1.20.1
```

### Envy Version

1.1.4

### Minecraft Version

1.20.1

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Meesterbouwer123** [comment]
this should be fixed now, looking at the history there were a lot of commits continuously adding and removing that part (all of them were made by me)
