### ISSUE TITLE
[Bug] java.lang.NullPointerException: Cannot invoke "java.io.InputStream.read(byte[])" because "in" is null

### ISSUE THREAD

**Issue by Abelkrijgtalles** [Volcanware/Envy-Client#31]
### Describe the bug

The game crashes when Envy Client is initizalizing.
https://mclo.gs/2eh7ZnG

### Steps to reproduce

```bash
Use the newest Simply Optimized, Envy Client, NoChatReports and the Baritone api. Then try to launch the game trough Prism Launcher.
Versions of Minecraft and mods:
https://github.com/Volcanware/Envy-Client/assets/56084910/3e4d409f-bf0e-4323-82ac-31e058880f2d
https://github.com/Volcanware/Envy-Client/assets/56084910/f7c232b2-2dae-431b-8178-5b6d00780651
```

### Envy Version

1.1.4

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by fluorek** [comment]
I have the same problem

**Comment by fluorek** [comment]
bro
update fabric

**Comment by Meesterbouwer123** [comment]
this should be fixed in the latest commit, can you verify it's fixed?

**Comment by fluorek** [comment]
change to "fabricloader": ">=0.15.0"
